from typing import Dict, Tuple, List

BASE_STATS: List[str] = [
    "pts", "min", "fga", "fta", "fg3a", "fgm", "ftm", "fg3m",
    "fg_pct", "fg3_pct", "ft_pct", "efg_pct", "ts_pct", "nba_fantasy_pts",
    "usage_rate",  "poss", "def_rating", "off_rating", "net_rating",
    "pfd", "pie", "pct_pts_3pt", "pct_pts_2pt", "pct_pts_2pt_mr",
    "pct_pts_ft", "pct_ast_2pm", "pct_uast_2pm",
    "pct_ast_3pm", "pct_uast_3pm", "ast", "tov", "plus_minus", 
    "p_ml", "abs_spread", "teim", "opim", 
]

TEAM_STATS: List[str] = [
   "team_pace", "team_off_rating", "team_def_rating", "team_net_rating", # Added def/net
    "team_ast", "team_ast_ratio",
    "team_tm_tov_pct", "team_efg_pct", "team_ts_pct", "team_poss",
    "team_pct_pts_3pt", "team_pct_pts_2pt", "team_pct_pts_2pt_mr",
    "team_pct_pts_ft", "team_pct_ast_2pm", "team_pct_uast_2pm",
    "team_pct_ast_3pm", "team_pct_uast_3pm", "team_pts", "team_travel_distance",
    "team_pf", "star1_out_flag", "star2_out_flag"
]

OPP_STATS: List[str] = [
    "opponent_pace", "opponent_off_rating", "opponent_def_rating", "opponent_net_rating", # Added off/net
    "opponent_dreb_pct", "opponent_tm_tov_pct", "opponent_efg_pct", "opponent_ts_pct", # Added more opp stats
    "opponent_pf"
]

PLAYER_ADVANCED_TRACKING: List[str] = [
    "player_game_speed", "player_game_dist", "player_game_oreb_c",
    "player_game_dreb_c", "reb_c", "player_game_touches",
    "player_game_screen_ast", "player_game_ft_ast", "passes",
    "player_game_c_fgm", "player_game_c_fga",
    "player_game_c_fg_pct", "player_game_u_fgm", "player_game_u_fga",
    "u_fg_pct", "fg_pct", "d_fgm",
    "d_fga", "d_fg_pct",
    "player_game_dist_per_min", "player_game_touches_per_min", "player_game_passes_per_min", "player_game_ast_per_min",
    "player_game_screen_ast_per_min", "player_game_passes_per_touch",
    "player_game_ast_per_touch", "player_game_high_value_touch_pct", "player_game_ast_conversion_pct",
    "player_game_contest_share", "player_game_uncontest_share",
    "player_game_cfg_diff", "player_game_weighted_fg_pct", "player_game_defensive_activity",
    "defended_shot_share", "player_game_speed_x_min", "player_game_dist_minus_expected",
    "player_game_touches_x_speed", "passes_x_contest_share",
    "player_game_is_starter", "player_game_is_bench", "player_game_bench_min", "player_game_starter_min", "player_game_is_available", "player_game_is_injury",
    "player_game_fga_per75", "player_game_fgm_per75", "player_game_fta_per75", "player_game_fg3a_per75",
    "player_game_touches_per75", "player_game_passes_per75", "player_game_pts_per75", "player_game_pfd_per75",
    "player_game_dist_per75", "player_game_nba_fantasy_pts_per75", "player_game_defended_shot_share_per75",
    "player_game_opponent_vs_player_fgm_allowed_per75", "player_game_opponent_vs_player_pts_allowed_per75", "player_game_opponent_vs_player_fga_allowed_per75", "player_game_fga_per_touch",
    "player_game_fga_per_poss", "player_game_nba_fantasy_pts_per_poss", "player_game_fta_per_poss", "player_game_pfd_per_poss",
    "player_game_ast_per_poss", "player_game_fg3a_per_poss", "player_game_passes_per_poss", "player_game_defended_shot_share_per_poss",
    "player_game_touches_per_poss", "player_game_dist_per_poss", "player_game_speed_per_poss", "player_game_opponent_vs_player_fga_allowed_per_poss",
    "player_game_opponent_vs_player_fgm_allowed_per_poss", "player_game_opponent_vs_player_pts_allowed_per_poss",  "star2_out_flag", "star1_out_flag",
    "player_game_ftm_per75", "player_game_fg3m_per75", "player_game_ast_per75",  "min_share_of_game", "pace_adj_minutes_100",

]



INTERACTIONS: Dict[str, tuple[str, str]] = {
 "composite_d_composite_o": ("composite_d", "composite_o"), "composite_o_usage_rate": ("composite_o", "usage_rate"), "composite_o_poss": ("composite_o", "poss"), "composite_o_min": ("composite_o", "min"),
  "composite_o_player_game_fga_per75": ("composite_o", "player_game_fga_per75"), "composite_o_player_game_fgm_per75": ("composite_o", "player_game_fgm_per75"), "composite_o_player_game_pts_per75": ("composite_o", "player_game_pts_per75"), "composite_o_ts_pct": ("composite_o", "ts_pct"),
  "ast_opponent_vs_player_pts_allowed": ("ast", "opponent_vs_player_pts_allowed"), "ast_pct_team_tm_tov_pct": ("ast_pct", "team_tm_tov_pct"), "ast_pie": ("ast", "pie"), "ast_rs_mr_fg_pct": ("ast", "rs_mr_fg_pct"),
  "ast_to_pie": ("ast_to", "pie"), "ast_to_rs_drive_fg_pct": ("ast_to", "rs_drive_fg_pct"), "ast_ts_pct": ("ast", "ts_pct"), "catch_and_shoot_synergy": ("pct_ast_3pm", "team_pct_pts_3pt"),
  "composite_composite_o": ("composite", "composite_o"), "composite_o_opp_rs_2p_plusminus": ("composite_o", "opp_rs_2p_plusminus"), "composite_o_opp_rs_3p_plusminus": ("composite_o", "opp_rs_3p_plusminus"), "composite_o_opp_rs_ov_pct_plusminus": ("composite_o", "opp_rs_ov_pct_plusminus"),
  "composite_o_pfd": ("composite_o", "pfd"), "composite_o_playoff_round": ("composite_o", "playoff_round"), "composite_o_rs_ab_fga": ("composite_o", "rs_ab_fga"), "composite_o_rs_cs_fga": ("composite_o", "rs_cs_fga"),
  "composite_o_rs_drives": ("composite_o", "rs_drives"), "composite_o_rs_mr_fga": ("composite_o", "rs_mr_fga"), "composite_o_rs_paint_touch_fg_pct": ("composite_o", "rs_paint_touch_fg_pct"), "composite_o_rs_paint_touches": ("composite_o", "rs_paint_touches"),
  "composite_o_rs_post_touches": ("composite_o", "rs_post_touches"), "composite_o_rs_ra_fga": ("composite_o", "rs_ra_fga"), "composite_o_series_number": ("composite_o", "series_number"), "composite_o_total_line": ("composite_o", "total_line"),
  "composite_opp_rs_2p_plusminus": ("composite", "opp_rs_2p_plusminus"), "composite_opp_rs_3p_plusminus": ("composite", "opp_rs_3p_plusminus"), "composite_opp_rs_ov_pct_plusminus": ("composite", "opp_rs_ov_pct_plusminus"), "dreb_e_off_rating": ("dreb", "e_off_rating"),
  "dreb_fg_pct": ("dreb", "fg_pct"), "dreb_pie": ("dreb", "pie"), "e_net_rating_def_rating": ("e_net_rating", "def_rating"), "fg3_pct_opp_rs_fg3_pct": ("fg3_pct", "opp_rs_fg3_pct"),
  "fg3_pct_opponent_vs_player_pts_allowed": ("fg3_pct", "opponent_vs_player_pts_allowed"), "fg3_pct_pct_pts_2pt": ("fg3_pct", "pct_pts_2pt"), "fg3_pct_rs_cs_fg3a": ("fg3_pct", "rs_cs_fg3a"), "fg3a_opp_rs_3p_freq": ("fg3a", "opp_rs_3p_freq"),
  "fg3a_opp_rs_3p_plusminus": ("fg3a", "opp_rs_3p_plusminus"), "fg3a_pct_fga_2pt": ("fg3a", "pct_fga_2pt"), "fg3a_pie": ("fg3a", "pie"), "fg3a_rs_onoff_pts_diff": ("fg3a", "rs_onoff_pts_diff"),
  "fg3a_ts_pct": ("fg3a", "ts_pct"), "fg3m_pct_pts_2pt": ("fg3m", "pct_pts_2pt"), "fg3m_pie": ("fg3m", "pie"), "fg3m_rs_ra_fga": ("fg3m", "rs_ra_fga"),
  "fg3m_ts_pct": ("fg3m", "ts_pct"), "fg_pct_opp_rs_d_fg_pct": ("fg_pct", "opp_rs_d_fg_pct"), "fga_ast": ("fga", "ast"), "fga_c_fg_pct": ("fga", "player_game_c_fg_pct"),
  "fga_contest_share": ("fga", "player_game_contest_share"), "fga_d_fg_pct": ("fga", "d_fg_pct"), "fga_defended_shot_share": ("fga", "defended_shot_share"), "fga_dist_minus_expected": ("fga", "player_game_dist_minus_expected"),
  "fga_e_off_rating": ("fga", "e_off_rating"), "fga_fg3a": ("fga", "fg3a"), "fga_is_elimination_game": ("fga", "is_elimination_game"), "fga_min": ("fga", "min"),
  "fga_nba_fantasy_pts": ("fga", "nba_fantasy_pts"), "fga_opp_pos_on_off_def_rating": ("fga", "opp_pos_on_off_def_rating"), "fga_opp_pos_on_off_dreb": ("fga", "opp_pos_on_off_dreb"), "fga_opp_pos_on_on_poss": ("fga", "opp_pos_on_on_poss"),
  "fga_opponent_efg_pct": ("fga", "opponent_efg_pct"), "fga_opponent_pf": ("fga", "opponent_pf"), "fga_passes_per_touch": ("fga", "player_game_passes_per_touch"), "fga_pie": ("fga", "pie"),
  "fga_player_age": ("fga", "player_age"), "fga_starter_min": ("fga", "player_game_starter_min"), "usage_rate_starter_min": ("usage_rate", "player_game_starter_min"), "fga_rs_cs_efg_pct": ("fga", "rs_cs_efg_pct"),
  "fga_rs_drive_pts_pct": ("fga", "rs_drive_pts_pct"), "fga_rs_on_on_pf": ("fga", "rs_on_on_pf"), "fga_rs_onoff_pts_diff": ("fga", "rs_onoff_pts_diff"), "fga_rs_paint_fg_pct": ("fga", "rs_paint_fg_pct"),
  "fga_rs_pu_efg_pct": ("fga", "rs_pu_efg_pct"), "fga_rs_ra_fg_pct": ("fga", "rs_ra_fg_pct"), "fga_series_number": ("fga", "series_number"), "fga_series_record": ("fga", "series_record"),
  "fga_team_ast_ratio": ("fga", "team_ast_ratio"), "fga_team_pct_ast_3pm": ("fga", "team_pct_ast_3pm"), "fga_team_pct_pts_2pt": ("fga", "team_pct_pts_2pt"), "fga_team_pf": ("fga", "team_pf"),
  "fga_total_line": ("fga", "total_line"), "fga_touches_per_min": ("fga", "player_game_touches_per_min"), "fga_ts_pct": ("fga", "ts_pct"), "fga_u_fg_pct": ("fga", "u_fg_pct"),
  "fga_uncontest_share": ("fga", "player_game_uncontest_share"), "fga_usage_rate": ("fga", "usage_rate"), "fgm_fg3m": ("fgm", "fg3m"), "foul_line_pressure": ("pct_pts_ft", "fta"),
  "ft_pct_efg_pct": ("ft_pct", "efg_pct"), "fta_pfd": ("fta", "pfd"), "fta_rs_onoff_pts_diff": ("fta", "rs_onoff_pts_diff"), "fta_ts_pct": ("fta", "ts_pct"),
  "ftm_total_line": ("ftm", "total_line"), "midrange_alpha": ("pct_pts_2pt_mr", "usage_rate"), "min_fgm": ("min", "fgm"), "min_game_in_series": ("min", "series_record"),
  "min_is_elimination_game": ("min", "is_elimination_game"), "min_pie": ("min", "pie"), "min_rs_drive_fga": ("min", "rs_drive_fga"), "min_rs_drives": ("min", "rs_cs_fga"),
  "min_rs_onoff_fga_diff": ("min", "rs_onoff_fga_diff"), "min_rs_paint_fga": ("min", "rs_paint_fga"), "min_usage_rate": ("min", "usage_rate"), "nb_fp_opp_rs_2p_plusminus": ("nba_fantasy_pts", "opp_rs_2p_plusminus"),
  "nb_fp_opp_rs_3p_plusminus": ("nba_fantasy_pts", "opp_rs_3p_plusminus"), "nb_fp_opp_rs_ov_pct_plusminus": ("nba_fantasy_pts", "opp_rs_ov_pct_plusminus"), "nb_fp_pts_opp_pos_on_off_pace": ("nba_fantasy_pts", "opp_pos_on_off_pace"), "nba_fantasy_pts_opp_rs_lt6f_freq": ("nba_fantasy_pts", "opp_rs_lt6f_freq"),
  "nba_fantasy_pts_total_line": ("nba_fantasy_pts", "total_line"), "nba_fantasy_pts_ts_pct": ("nba_fantasy_pts", "ts_pct"), "nba_fantasy_pts_composite_o": ("nba_fantasy_pts", "composite_o"), "nba_fantasy_ptsrs_ab_fga": ("nba_fantasy_pts", "rs_ab_fga"),
  "nba_fantasy_ptsrs_cs_fga": ("nba_fantasy_pts", "rs_cs_fga"), "nba_fantasy_ptsrs_drives": ("nba_fantasy_pts", "rs_drives"), "nba_fantasy_ptsrs_mr_fga": ("nba_fantasy_pts", "rs_mr_fga"), "nba_fantasy_ptsrs_paint_touches": ("nba_fantasy_pts", "rs_paint_touches"),
  "nba_fantasy_ptsrs_post_touches": ("nba_fantasy_pts", "rs_post_touches"), "nba_fantasy_ptsrs_pu_fga": ("nba_fantasy_pts", "rs_pu_fga"), "nba_fantasy_ptsrs_ra_fga": ("nba_fantasy_pts", "rs_ra_fga"), "off_rating_rs_cs_efg_pct": ("off_rating", "rs_cs_efg_pct"),
  "off_rating_rs_cs_fg3a": ("off_rating", "rs_cs_fg3a"), "pct_ast_3pm_def_rating": ("pct_ast_3pm", "def_rating"), "pct_pts_2pt_mr_opp_rs_gt15f_plusminus": ("pct_pts_2pt_mr", "opp_rs_gt15f_plusminus"), "pct_pts_3pt_opp_rs_3p_plusminus": ("pct_pts_3pt", "opp_rs_3p_plusminus"),
  "pct_pts_3pt_pct_pts_2pt": ("pct_pts_3pt", "pct_pts_2pt"), "pct_pts_3pt_team_pts": ("pct_pts_3pt", "team_pts"), "pct_pts_ft_team_pts": ("pct_pts_ft", "team_pts"), "pct_uast_2pm_opponent_vs_player_pts_allowed": ("pct_uast_2pm", "opponent_vs_player_pts_allowed"),
  "pct_uast_2pm_pct_ast_2pm": ("pct_uast_2pm", "pct_ast_2pm"), "pct_uast_2pm_pct_pts_3pt": ("pct_uast_2pm", "pct_pts_3pt"), "pfd_rs_drives": ("pfd", "rs_drives"), "pfd_rs_mr_fg_pct": ("pfd", "rs_mr_fg_pct"),
  "pfd_rs_paint_touches": ("pfd", "rs_paint_touches"), "pfd_ts_pct": ("pfd", "ts_pct"), "pie_pf": ("pie", "pf"), "poss_off_rating": ("poss", "off_rating"),
  "poss_opp_pos_on_off_off_rating": ("poss", "opp_pos_on_off_off_rating"), "poss_starter_min": ("poss", "player_game_starter_min"), "poss_playoff_round": ("poss", "playoff_round"), "poss_rs_drive_fg_pct": ("poss", "rs_drive_fg_pct"),
  "poss_rs_on_on_pie": ("poss", "rs_on_on_pie"), "poss_rs_on_on_poss": ("poss", "rs_on_on_poss"), "poss_rs_paint_touch_pts_pct": ("poss", "rs_paint_touch_pts_pct"), "poss_total_line": ("poss", "total_line"),
  "poss_ts_pct": ("poss", "ts_pct"), "pts_composite": ("pts", "composite"), "pts_opponent_pf": ("pts", "opponent_pf"), "pts_pfd": ("pts", "pfd"),
  "pts_pie": ("pts", "pie"), "pts_usage_rate": ("pts", "usage_rate"), "reb_opponent_vs_player_pts_allowed": ("reb", "opponent_vs_player_pts_allowed"), "reb_rs_cs_efg_pct": ("reb", "rs_cs_efg_pct"),
  "rs_cs_fg3a_pie": ("rs_cs_fg3a", "pie"), "rs_cs_fg3a_rs_paint_fg_pct": ("rs_cs_fg3a", "rs_paint_fg_pct"), "rs_drive_fga_pie": ("rs_drive_fga", "pie"), "rs_drives_fg3_pct": ("rs_drives", "fg3_pct"),
  "rs_drives_ft_pct": ("rs_drives", "ft_pct"), "rs_drives_off_rating": ("rs_drives", "off_rating"), "rs_drives_reb": ("rs_drives", "reb"), "rs_drives_rs_paint_touch_pts_pct": ("rs_drives", "rs_paint_touch_pts_pct"),
  "rs_on_on_pts_usage_rate": ("rs_on_on_pts", "usage_rate"), "rs_paint_fga_pie": ("rs_paint_fga", "pie"), "rs_paint_fga_rs_ab_fga": ("rs_paint_fga", "rs_ab_fga"), "rs_paint_fga_total_line": ("rs_paint_fga", "total_line"),
  "rs_paint_fgm_off_rating": ("rs_paint_fgm", "off_rating"), "rs_pu_fga_ft_pct": ("rs_pu_fga", "ft_pct"), "rs_pu_fga_rs_drive_pts_pct": ("rs_pu_fga", "rs_drive_pts_pct"), "rs_pu_fga_rs_ra_fgm": ("rs_pu_fga", "rs_ra_fgm"),
  "rs_ra_fga_ft_pct": ("rs_ra_fga", "ft_pct"), "rs_ra_fgm_opponent_vs_player_pts_allowed": ("rs_ra_fgm", "opponent_vs_player_pts_allowed"), "rs_ra_fgm_ts_pct": ("rs_ra_fgm", "ts_pct"), "team_pace_rs_onoff_pts_diff": ("team_pace", "rs_onoff_pts_diff"),
  "three_point_dependency": ("pct_pts_3pt", "fg3a"), "tov_off_rating": ("tov", "off_rating"), "tov_pie": ("tov", "pie"), "ts_pct_opp_rs_d_fg_pct": ("ts_pct", "opp_rs_d_fg_pct"),
  "unassisted_2pt_usage": ("pct_uast_2pm", "usage_rate"), "usage_rate_composite": ("usage_rate", "composite"), "usage_rate_opp_rs_d_fgm": ("usage_rate", "opp_rs_d_fgm"), "usage_rate_rs_cs_efg_pct": ("usage_rate", "rs_cs_efg_pct"),
  "usage_rate_rs_drive_fg_pct": ("usage_rate", "rs_drive_fg_pct"), "usage_rate_rs_drives": ("usage_rate", "rs_cs_fga"), "usage_rate_rs_mr_fgm": ("usage_rate", "rs_mr_fgm"), "usage_rate_rs_on_on_poss": ("usage_rate", "rs_on_on_poss"),
  "usage_rate_rs_onoff_pts_diff": ("usage_rate", "rs_onoff_pts_diff"), "usage_rate_rs_paint_fga": ("usage_rate", "rs_paint_fga"), "usage_rate_rs_paint_touches": ("usage_rate", "rs_paint_touches"), "usage_rate_rs_ra_fga": ("usage_rate", "rs_ra_fga"),
  "usage_rate_series_record": ("usage_rate", "series_record"), "usage_rate_ts_pct": ("usage_rate", "ts_pct"), "poss_usage_rate": ("poss", "usage_rate"), "usage_rate_speed_x_min": ("usage_rate", "player_game_speed_x_min"),
  "player_game_touches_speed_x_min": ("player_game_touches", "player_game_speed_x_min"), "poss_speed_x_min": ("poss", "player_game_speed_x_min"), "min_ts_pct": ("min", "ts_pct"), "poss_rs_on_on_pts": ("poss", "rs_on_on_pts"),
  "poss_rs_on_on_pfd": ("poss", "rs_on_on_pfd"), "fga_efg_pct": ("fga", "efg_pct"), "fga_fg_pct": ("fga", "fg_pct"), "fga_off_rating": ("fga", "off_rating"),
  "fga_team_ts_pct": ("fga", "team_ts_pct"), "fga_team_efg_pct": ("fga", "team_efg_pct"), "fga_team_e_off_rating": ("fga", "team_e_off_rating"), "fga_team_off_rating": ("fga", "team_off_rating"),
  "fga_opponent_def_rating": ("fga", "opponent_def_rating"), "fga_team_pts": ("fga", "team_pts"), "fga_weighted_fg_pct": ("fga", "player_game_weighted_fg_pct"), "fga_rs_on_on_ts_pct": ("fga", "rs_on_on_ts_pct"),
  "fga_rs_on_on_efg_pct": ("fga", "rs_on_on_efg_pct"), "fga_rs_on_on_off_rating": ("fga", "rs_on_on_off_rating"), "fga_player_height": ("fga", "player_height"), "fga_opp_rs_d_fg_pct": ("fga", "opp_rs_d_fg_pct"),
  "fga_opp_rs_fg2_pct": ("fga", "opp_rs_fg2_pct"), "fga_opp_rs_lt_10_pct": ("fga", "opp_rs_lt_10_pct"), "fga_opp_pos_on_on_def_rating": ("fga", "opp_pos_on_on_def_rating"), "fga_rs_on_on_pie": ("fga", "rs_on_on_pie"),
  "fga_opp_rs_lt_06_pct": ("fga", "opp_rs_lt_06_pct"), "fga_opp_rs_gt_15_pct": ("fga", "opp_rs_gt_15_pct"), "fga_opp_rs_fg3_pct": ("fga", "opp_rs_fg3_pct"), "fga_rs_on_off_pace": ("fga", "rs_on_off_pace"),
  "fga_opp_pos_on_on_pace": ("fga", "opp_pos_on_on_pace"), "fga_opp_pos_on_off_pace": ("fga", "opp_pos_on_off_pace"), "fga_opp_rs_d_fgm": ("fga", "opp_rs_d_fgm"), "fga_rs_on_on_pace": ("fga", "rs_on_on_pace"),
  "fga_dist_per_min": ("fga", "player_game_dist_per_min"), "fga_speed": ("fga", "player_game_speed"), "fga_rs_on_off_ts_pct": ("fga", "rs_on_off_ts_pct"), "fga_rs_on_off_efg_pct": ("fga", "rs_on_off_efg_pct"),
  "fga_opp_pos_on_off_off_rating": ("fga", "opp_pos_on_off_off_rating"), "fga_opp_rs_d_fga": ("fga", "opp_rs_d_fga"), "fga_team_min": ("fga", "team_min"), "fga_rs_on_off_def_rating": ("fga", "rs_on_off_def_rating"),
  "fga_rs_on_on_def_rating": ("fga", "rs_on_on_def_rating"), "fga_rs_on_off_off_rating": ("fga", "rs_on_off_off_rating"), "fga_team_pace": ("fga", "team_pace"), "fga_opponent_pace": ("fga", "opponent_pace"),
  "fga_opp_rs_lt10f_freq": ("fga", "opp_rs_lt10f_freq"), "fga_opp_pos_on_on_off_rating": ("fga", "opp_pos_on_on_off_rating"), "fga_team_e_pace": ("fga", "team_e_pace"), "fga_rs_on_on_ast_ratio": ("fga", "rs_on_on_ast_ratio"),
  "fga_is_available": ("fga", "player_game_is_available"), "fga_team_poss": ("fga", "team_poss"), "fga_opp_rs_2p_freq": ("fga", "opp_rs_2p_freq"), "fga_opp_rs_lt6f_freq": ("fga", "opp_rs_lt6f_freq"),
  "fga_pace": ("fga", "pace"), "fga_pace_per40": ("fga", "pace_per40"), "fga_opp_rs_gt15f_freq": ("fga", "opp_rs_gt15f_freq"), "fga_e_pace": ("fga", "e_pace"),
  "fga_rs_on_off_pie": ("fga", "rs_on_off_pie"), "fga_rs_on_on_ast_pct": ("fga", "rs_on_on_ast_pct"), "fga_rs_on_off_ast_pct": ("fga", "rs_on_off_ast_pct"), "fga_opp_pos_on_off_pie": ("fga", "opp_pos_on_off_pie"),
  "fga_team_pie": ("fga", "team_pie"), "fga_rs_on_off_ast_ratio": ("fga", "rs_on_off_ast_ratio"), "fga_opp_rs_3p_freq": ("fga", "opp_rs_3p_freq"), "fga_opp_pos_on_on_pie": ("fga", "opp_pos_on_on_pie"),
  "fga_rs_on_off_tm_tov_pct": ("fga", "rs_on_off_tm_tov_pct"), "fga_team_def_rating": ("fga", "team_def_rating"), "fga_opponent_off_rating": ("fga", "opponent_off_rating"), "fga_opponent_dreb_pct": ("fga", "opponent_dreb_pct"),
  "fga_opponent_ts_pct": ("fga", "opponent_ts_pct"), "fga_rs_on_on_tm_tov_pct": ("fga", "rs_on_on_tm_tov_pct"), "fga_poss": ("fga", "poss"), "fga_passes_per_min": ("fga", "player_game_passes_per_min"),
  "fga_rs_drive_fg_pct": ("fga", "rs_drive_fg_pct"), "fga_rs_on_on_ast_to": ("fga", "rs_on_on_ast_to"), "fga_rs_on_off_ast_to": ("fga", "rs_on_off_ast_to"), "fga_def_rating": ("fga", "def_rating"),
  "fga_e_def_rating": ("fga", "e_def_rating"), "fga_speed_x_min": ("fga", "player_game_speed_x_min"), "fga_dist": ("fga", "player_game_dist"), "fga_rs_on_on_pts": ("fga", "rs_on_on_pts"),
  "fga_rs_on_on_fga": ("fga", "rs_on_on_fga"), "fga_rs_on_on_reb": ("fga", "rs_on_on_reb"), "fga_rs_on_on_dreb": ("fga", "rs_on_on_dreb"), "fga_rs_on_on_fgm": ("fga", "rs_on_on_fgm"),
  "fga_rs_on_on_pfd": ("fga", "rs_on_on_pfd"), "fga_rs_paint_touch_fg_pct": ("fga", "rs_paint_touch_fg_pct"), "fga_team_ast": ("fga", "team_ast"), "fga_rs_on_on_fta": ("fga", "rs_on_on_fta"),
  "fga_rs_on_on_ftm": ("fga", "rs_on_on_ftm"), "fga_rs_on_on_fg3a": ("fga", "rs_on_on_fg3a"), "fga_rs_on_on_fg3m": ("fga", "rs_on_on_fg3m"), "fga_rs_on_on_oreb": ("fga", "rs_on_on_oreb"),
  "fga_opp_pos_on_off_pf": ("fga", "opp_pos_on_off_pf"), "fga_rs_cs_fg3_pct": ("fga", "rs_cs_fg3_pct"), "poss_pie": ("poss", "pie"), "fgm_opp_rs_lt10f_freq": ("fgm", "opp_rs_lt10f_freq"),
  "poss_rs_on_on_fgm": ("poss", "rs_on_on_fgm"), "poss_rs_on_on_fta": ("poss", "rs_on_on_fta"), "nba_fantasy_pts_pace_per40": ("nba_fantasy_pts", "pace_per40"), "poss_rs_paint_fga": ("poss", "rs_paint_fga"),
  "ast_pct_ast": ("ast_pct", "ast"), "ast_pct_defensive_activity": ("ast_pct", "player_game_defensive_activity"), "composite_hv_touch_pct": ("composite", "player_game_high_value_touch_pct"), "composite_o_ast_conversion_pct": ("composite_o", "player_game_ast_conversion_pct"),
  "composite_o_contest_share": ("composite_o", "player_game_contest_share"), "composite_o_oreb_c": ("composite_o", "player_game_oreb_c"), "composite_o_uncontest_share": ("composite_o", "player_game_uncontest_share"), "composite_speed_x_min": ("composite", "player_game_speed_x_min"),
  "composite_weighted_fg_pct": ("composite", "player_game_weighted_fg_pct"), "dist_pct_pts_3pt": ("player_game_dist", "pct_pts_3pt"), "efg_pct_player_touches": ("efg_pct", "player_game_touches_per_min"), "fg3m_pct_fga_2pt": ("fg3m", "pct_fga_2pt"),
  "fga_player_game_bench_min": ("fga", "player_game_bench_min"), "fga_rs_paint_fgm": ("fga", "rs_paint_fgm"), "fgm_min_numeric": ("fgm", "min_numeric"), "fgm_opp_pos_on_off_def_rating": ("fgm", "opp_pos_on_off_def_rating"),
  "fgm_passes_per_touch": ("fgm", "passes_per_touch"), "fgm_player_game_bench_min": ("fgm", "player_game_bench_min"), "fgm_player_game_contest_share": ("fgm", "player_game_contest_share"), "fgm_player_game_dist_minus_expected": ("fgm", "player_game_dist_minus_expected"),
  "fgm_player_game_dreb_c_ratio": ("fgm", "player_game_dreb_c_ratio"), "fgm_player_game_reb_c_per_min": ("fgm", "player_game_reb_c_per_min"), "fgm_player_game_speed_per_poss": ("fgm", "player_game_speed_per_poss"), "fgm_player_game_starter_min": ("fgm", "player_game_starter_min"),
  "fgm_player_game_touches_per_poss": ("fgm", "player_game_touches_per_poss"), "fgm_player_game_u_fg_pct": ("fgm", "player_game_u_fg_pct"), "fgm_player_game_uncontest_share": ("fgm", "player_game_uncontest_share"), "fgm_player_game_weighted_fg_pct": ("fgm", "player_game_weighted_fg_pct"),
  "fgm_pt_cut_poss_weighted_ppp": ("fgm", "pt_cut_poss_weighted_ppp"), "fgm_pt_handler_poss_weighted_ppp": ("fgm", "pt_handler_poss_weighted_ppp"), "fgm_pt_handoff_poss_weighted_ppp": ("fgm", "pt_handoff_poss_weighted_ppp"), "fgm_pt_iso_poss_weighted_ppp": ("fgm", "pt_iso_poss_weighted_ppp"),
  "fgm_pt_mis_poss_weighted_ppp": ("fgm", "pt_mis_poss_weighted_ppp"), "fgm_pt_offscreen_poss_weighted_ppp": ("fgm", "pt_offscreen_poss_weighted_ppp"), "fgm_pt_postup_poss_weighted_ppp": ("fgm", "pt_postup_poss_weighted_ppp"), "fgm_pt_putback_poss_weighted_ppp": ("fgm", "pt_putback_poss_weighted_ppp"),
  "fgm_pt_rollman_poss_weighted_ppp": ("fgm", "pt_rollman_poss_weighted_ppp"), "fgm_pt_spotup_poss_weighted_ppp": ("fgm", "pt_spotup_poss_weighted_ppp"), "fgm_pt_transition_poss_weighted_ppp": ("fgm", "pt_transition_poss_weighted_ppp"), "fgm_rs_cs_efg_pct": ("fgm", "rs_cs_efg_pct"),
  "fgm_series_number": ("fgm", "series_number"), "fgm_team_pie": ("fgm", "team_pie"), "fgm_total_line": ("fgm", "total_line"), "ftm_speed_x_min": ("ftm", "player_game_speed_x_min"),
  "ftm_u_fg_pct": ("ftm", "u_fg_pct"), "ftm_uncontest_share": ("ftm", "player_game_uncontest_share"), "min_share_of_game_pt_handler_adj_ppp": ("min_share_of_game", "pt_handler_adj_ppp"), "min_uncontest_share": ("min", "player_game_uncontest_share"),
  "nba_fantasy_pts_uncontest_share": ("nba_fantasy_pts", "player_game_uncontest_share"), "off_rating_touches": ("off_rating", "player_game_touches"), "opponent_vs_player_pts_allowed_c_fg_pct": ("opponent_vs_player_pts_allowed", "player_game_c_fg_pct"), "opponent_vs_player_pts_allowed_passes_x_contest_share": ("opponent_vs_player_pts_allowed", "passes_x_contest_share"),
  "opponent_vs_player_pts_allowed_touches": ("opponent_vs_player_pts_allowed", "player_game_touches"), "opponent_vs_player_pts_allowed_u_fg_pct": ("opponent_vs_player_pts_allowed", "u_fg_pct"), "opponent_vs_player_pts_allowed_weighted_fg_pct": ("opponent_vs_player_pts_allowed", "player_game_weighted_fg_pct"), "passes_touch_x_ast_conv": ("player_game_passes_per_touch", "player_game_ast_conversion_pct"),
  "pct_pts_3pt_ast": ("pct_pts_3pt", "ast"), "pct_pts_3pt_c_fg_pct": ("pct_pts_3pt", "player_game_c_fg_pct"), "pct_pts_3pt_passes": ("pct_pts_3pt", "passes"), "pct_pts_3pt_passes_x_contest_share": ("pct_pts_3pt", "passes_x_contest_share"),
  "pfd_total_line": ("pfd", "total_line"), "player_game_pts_per75_rs_on_on_pts": ("player_game_pts_per75", "rs_on_on_pts"), "poss_player_game_bench_min": ("poss", "player_game_bench_min"), "poss_player_game_dist": ("poss", "player_game_dist"),
  "poss_player_game_pts_per75": ("poss", "player_game_pts_per75"), "poss_pt_cut_adj_ppp": ("poss", "pt_cut_adj_ppp"), "poss_pt_handoff_adj_ppp": ("poss", "pt_handoff_adj_ppp"), "poss_pt_iso_poss_weighted_ppp": ("poss", "pt_iso_poss_weighted_ppp"),
  "poss_pt_mis_adj_ppp": ("poss", "pt_mis_adj_ppp"), "poss_pt_offscreen_poss_weighted_ppp": ("poss", "pt_offscreen_poss_weighted_ppp"), "poss_pt_postup_adj_ppp": ("poss", "pt_postup_adj_ppp"), "poss_pt_putback_adj_ppp": ("poss", "pt_putback_adj_ppp"),
  "poss_pt_spotup_adj_ppp": ("poss", "pt_spotup_adj_ppp"), "poss_rs_drive_pts_pct": ("poss", "rs_drive_pts_pct"), "poss_u_fg_pct": ("poss", "u_fg_pct"), "pt_cut_poss_per_g_opponent_dreb_pct": ("pt_cut_poss_per_g", "opponent_dreb_pct"),
  "pt_cut_poss_per_g_pt_rollman_poss_per_g": ("pt_cut_poss_per_g", "pt_rollman_poss_per_g"), "pt_cut_poss_per_g_rs_onoff_pace_diff": ("pt_cut_poss_per_g", "rs_onoff_pace_diff"), "pt_handler_poss_per_g_min_share_of_game": ("pt_handler_poss_per_g", "min_share_of_game"), "pt_handler_poss_per_g_total_line": ("pt_handler_poss_per_g", "total_line"),
  "pt_handoff_poss_per_g_team_pace": ("pt_handoff_poss_per_g", "team_pace"), "pt_iso_poss_per_g_min_share_of_game": ("pt_iso_poss_per_g", "min_share_of_game"), "pt_iso_poss_per_g_pt_handler_poss_per_g": ("pt_iso_poss_per_g", "pt_handler_poss_per_g"), "pt_iso_poss_per_g_pt_spotup_poss_per_g": ("pt_iso_poss_per_g", "pt_spotup_poss_per_g"),
  "pt_iso_poss_per_g_rs_onoff_net_rating_diff": ("pt_iso_poss_per_g", "rs_onoff_net_rating_diff"), "pt_iso_poss_per_g_total_line": ("pt_iso_poss_per_g", "total_line"), "pt_iso_ppp_player_game_opponent_vs_player_fgm_allowed_per75": ("pt_iso_ppp", "player_game_opponent_vs_player_fgm_allowed_per75"), "pt_iso_ppp_rs_on_on_ts_pct": ("pt_iso_ppp", "rs_on_on_ts_pct"),
  "pt_iso_ppp_rs_onoff_net_rating_diff": ("pt_iso_ppp", "rs_onoff_net_rating_diff"), "pt_iso_ppp_team_net_rating": ("pt_iso_ppp", "team_net_rating"), "pt_iso_ppp_total_line": ("pt_iso_ppp", "total_line"), "pt_mis_poss_per_g_team_pace": ("pt_mis_poss_per_g", "team_pace"),
  "pt_offscreen_poss_per_g_team_pace": ("pt_offscreen_poss_per_g", "team_pace"), "pt_postup_poss_per_g_team_pace": ("pt_postup_poss_per_g", "team_pace"), "pt_postup_ppp_opp_rs_2p_freq": ("pt_postup_ppp", "opp_rs_2p_freq"), "pt_postup_ppp_pt_iso_ppp": ("pt_postup_ppp", "pt_iso_ppp"),
  "pt_putback_poss_per_g_team_pace": ("pt_putback_poss_per_g", "team_pace"), "pt_rollman_poss_per_g_team_pace": ("pt_rollman_poss_per_g", "team_pace"), "pt_rollman_ppp_opp_rs_lt6f_freq": ("pt_rollman_ppp", "opp_rs_lt6f_freq"), "pt_spotup_poss_per_g_opp_rs_3p_freq": ("pt_spotup_poss_per_g", "opp_rs_3p_freq"),
  "pt_spotup_poss_per_g_player_game_fg3a_per_poss": ("pt_spotup_poss_per_g", "player_game_fg3a_per_poss"), "pt_spotup_ppp_opp_rs_3p_freq": ("pt_spotup_ppp", "opp_rs_3p_freq"), "pt_spotup_ppp_player_game_is_bench": ("pt_spotup_ppp", "player_game_is_bench"), "pt_spotup_ppp_player_game_opponent_vs_player_pts_allowed_per75": ("pt_spotup_ppp", "player_game_opponent_vs_player_pts_allowed_per75"),
  "pt_transition_poss_per_g_min_share_of_game": ("pt_transition_poss_per_g", "min_share_of_game"), "pt_transition_poss_per_g_player_game_passes_per_poss": ("pt_transition_poss_per_g", "player_game_passes_per_poss"), "pt_transition_poss_per_g_spread_line": ("pt_transition_poss_per_g", "spread_line"), "pt_transition_poss_per_g_team_pace": ("pt_transition_poss_per_g", "team_pace"),
  "pt_transition_poss_per_g_total_line": ("pt_transition_poss_per_g", "total_line"), "pt_transition_ppp_opponent_tm_tov_pct": ("pt_transition_ppp", "opponent_tm_tov_pct"), "pt_transition_ppp_player_game_speed": ("pt_transition_ppp", "player_game_speed"), "pt_transition_ppp_pt_spotup_ppp": ("pt_transition_ppp", "pt_spotup_ppp"),
  "rs_cs_fg3a_touches": ("rs_cs_fg3a", "player_game_touches"), "rs_on_on_fgm_usage_rate": ("rs_on_on_fgm", "usage_rate"), "rs_on_on_pfd_ts_pct": ("rs_on_on_pfd", "ts_pct"), "touches_total_line": ("player_game_touches", "total_line"),
  "touches_u_fg_pct": ("player_game_touches", "u_fg_pct"), "touches_weighted_fg_pct": ("player_game_touches", "player_game_weighted_fg_pct"),

}

INTERACTION_NAMES: List[str] = [
  "composite_d_composite_o", "composite_o_usage_rate", "composite_o_poss", "composite_o_min",
  "composite_o_player_game_fga_per75", "composite_o_player_game_fgm_per75", "composite_o_player_game_pts_per75", "composite_o_ts_pct",
  "ast_opponent_vs_player_pts_allowed", "ast_pct_team_tm_tov_pct", "ast_pie", "ast_rs_mr_fg_pct",
  "ast_to_pie", "ast_to_rs_drive_fg_pct", "ast_ts_pct", "catch_and_shoot_synergy",
  "composite_composite_o", "composite_o_opp_rs_2p_plusminus", "composite_o_opp_rs_3p_plusminus", "composite_o_opp_rs_ov_pct_plusminus",
  "composite_o_pfd", "composite_o_playoff_round", "composite_o_rs_ab_fga", "composite_o_rs_cs_fga",
  "composite_o_rs_drives", "composite_o_rs_mr_fga", "composite_o_rs_paint_touch_fg_pct", "composite_o_rs_paint_touches",
  "composite_o_rs_post_touches", "composite_o_rs_ra_fga", "composite_o_series_number", "composite_o_total_line",
  "composite_opp_rs_2p_plusminus", "composite_opp_rs_3p_plusminus", "composite_opp_rs_ov_pct_plusminus", "dreb_e_off_rating",
  "dreb_fg_pct", "dreb_pie", "e_net_rating_def_rating", "fg3_pct_opp_rs_fg3_pct",
  "fg3_pct_opponent_vs_player_pts_allowed", "fg3_pct_pct_pts_2pt", "fg3_pct_rs_cs_fg3a", "fg3a_opp_rs_3p_freq",
  "fg3a_opp_rs_3p_plusminus", "fg3a_pct_fga_2pt", "fg3a_pie", "fg3a_rs_onoff_pts_diff",
  "fg3a_ts_pct", "fg3m_pct_pts_2pt", "fg3m_pie", "fg3m_rs_ra_fga",
  "fg3m_ts_pct", "fg_pct_opp_rs_d_fg_pct", "fga_ast", "fga_c_fg_pct",
  "fga_contest_share", "fga_d_fg_pct", "fga_defended_shot_share", "fga_dist_minus_expected",
  "fga_e_off_rating", "fga_fg3a", "fga_is_elimination_game", "fga_min",
  "fga_nba_fantasy_pts", "fga_opp_pos_on_off_def_rating", "fga_opp_pos_on_off_dreb", "fga_opp_pos_on_on_poss",
  "fga_opponent_efg_pct", "fga_opponent_pf", "fga_passes_per_touch", "fga_pie",
  "fga_player_age", "fga_starter_min", "usage_rate_starter_min", "fga_rs_cs_efg_pct",
  "fga_rs_drive_pts_pct", "fga_rs_on_on_pf", "fga_rs_onoff_pts_diff", "fga_rs_paint_fg_pct",
  "fga_rs_pu_efg_pct", "fga_rs_ra_fg_pct", "fga_series_number", "fga_series_record",
  "fga_team_ast_ratio", "fga_team_pct_ast_3pm", "fga_team_pct_pts_2pt", "fga_team_pf",
  "fga_total_line", "fga_touches_per_min", "fga_ts_pct", "fga_u_fg_pct",
  "fga_uncontest_share", "fga_usage_rate", "fgm_fg3m", "foul_line_pressure",
  "ft_pct_efg_pct", "fta_pfd", "fta_rs_onoff_pts_diff", "fta_ts_pct",
  "ftm_total_line", "midrange_alpha", "min_fgm", "min_game_in_series",
  "min_is_elimination_game", "min_pie", "min_rs_drive_fga", "min_rs_drives",
  "min_rs_onoff_fga_diff", "min_rs_paint_fga", "min_usage_rate", "nb_fp_opp_rs_2p_plusminus",
  "nb_fp_opp_rs_3p_plusminus", "nb_fp_opp_rs_ov_pct_plusminus", "nb_fp_pts_opp_pos_on_off_pace", "nba_fantasy_pts_opp_rs_lt6f_freq",
  "nba_fantasy_pts_total_line", "nba_fantasy_pts_ts_pct", "nba_fantasy_pts_composite_o", "nba_fantasy_ptsrs_ab_fga",
  "nba_fantasy_ptsrs_cs_fga", "nba_fantasy_ptsrs_drives", "nba_fantasy_ptsrs_mr_fga", "nba_fantasy_ptsrs_paint_touches",
  "nba_fantasy_ptsrs_post_touches", "nba_fantasy_ptsrs_pu_fga", "nba_fantasy_ptsrs_ra_fga", "off_rating_rs_cs_efg_pct",
  "off_rating_rs_cs_fg3a", "pct_ast_3pm_def_rating", "pct_pts_2pt_mr_opp_rs_gt15f_plusminus", "pct_pts_3pt_opp_rs_3p_plusminus",
  "pct_pts_3pt_pct_pts_2pt", "pct_pts_3pt_team_pts", "pct_pts_ft_team_pts", "pct_uast_2pm_opponent_vs_player_pts_allowed",
  "pct_uast_2pm_pct_ast_2pm", "pct_uast_2pm_pct_pts_3pt", "pfd_rs_drives", "pfd_rs_mr_fg_pct",
  "pfd_rs_paint_touches", "pfd_ts_pct", "pie_pf", "poss_off_rating",
  "poss_opp_pos_on_off_off_rating", "poss_starter_min", "poss_playoff_round", "poss_rs_drive_fg_pct",
  "poss_rs_on_on_pie", "poss_rs_on_on_poss", "poss_rs_paint_touch_pts_pct", "poss_total_line",
  "poss_ts_pct", "pts_composite", "pts_opponent_pf", "pts_pfd",
  "pts_pie", "pts_usage_rate", "reb_opponent_vs_player_pts_allowed", "reb_rs_cs_efg_pct",
  "rs_cs_fg3a_pie", "rs_cs_fg3a_rs_paint_fg_pct", "rs_drive_fga_pie", "rs_drives_fg3_pct",
  "rs_drives_ft_pct", "rs_drives_off_rating", "rs_drives_reb", "rs_drives_rs_paint_touch_pts_pct",
  "rs_on_on_pts_usage_rate", "rs_paint_fga_pie", "rs_paint_fga_rs_ab_fga", "rs_paint_fga_total_line",
  "rs_paint_fgm_off_rating", "rs_pu_fga_ft_pct", "rs_pu_fga_rs_drive_pts_pct", "rs_pu_fga_rs_ra_fgm",
  "rs_ra_fga_ft_pct", "rs_ra_fgm_opponent_vs_player_pts_allowed", "rs_ra_fgm_ts_pct", "team_pace_rs_onoff_pts_diff",
  "three_point_dependency", "tov_off_rating", "tov_pie", "ts_pct_opp_rs_d_fg_pct",
  "unassisted_2pt_usage", "usage_rate_composite", "usage_rate_opp_rs_d_fgm", "usage_rate_rs_cs_efg_pct",
  "usage_rate_rs_drive_fg_pct", "usage_rate_rs_drives", "usage_rate_rs_mr_fgm", "usage_rate_rs_on_on_poss",
  "usage_rate_rs_onoff_pts_diff", "usage_rate_rs_paint_fga", "usage_rate_rs_paint_touches", "usage_rate_rs_ra_fga",
  "usage_rate_series_record", "usage_rate_ts_pct", "poss_usage_rate", "usage_rate_speed_x_min",
  "player_game_touches_speed_x_min", "poss_speed_x_min", "min_ts_pct", "poss_rs_on_on_pts",
  "poss_rs_on_on_pfd", "fga_efg_pct", "fga_fg_pct", "fga_off_rating",
  "fga_team_ts_pct", "fga_team_efg_pct", "fga_team_e_off_rating", "fga_team_off_rating",
  "fga_opponent_def_rating", "fga_team_pts", "fga_weighted_fg_pct", "fga_rs_on_on_ts_pct",
  "fga_rs_on_on_efg_pct", "fga_rs_on_on_off_rating", "fga_player_height", "fga_opp_rs_d_fg_pct",
  "fga_opp_rs_fg2_pct", "fga_opp_rs_lt_10_pct", "fga_opp_pos_on_on_def_rating", "fga_rs_on_on_pie",
  "fga_opp_rs_lt_06_pct", "fga_opp_rs_gt_15_pct", "fga_opp_rs_fg3_pct", "fga_rs_on_off_pace",
  "fga_opp_pos_on_on_pace", "fga_opp_pos_on_off_pace", "fga_opp_rs_d_fgm", "fga_rs_on_on_pace",
  "fga_dist_per_min", "fga_speed", "fga_rs_on_off_ts_pct", "fga_rs_on_off_efg_pct",
  "fga_opp_pos_on_off_off_rating", "fga_opp_rs_d_fga", "fga_team_min", "fga_rs_on_off_def_rating",
  "fga_rs_on_on_def_rating", "fga_rs_on_off_off_rating", "fga_team_pace", "fga_opponent_pace",
  "fga_opp_rs_lt10f_freq", "fga_opp_pos_on_on_off_rating", "fga_team_e_pace", "fga_rs_on_on_ast_ratio",
  "fga_is_available", "fga_team_poss", "fga_opp_rs_2p_freq", "fga_opp_rs_lt6f_freq",
  "fga_pace", "fga_pace_per40", "fga_opp_rs_gt15f_freq", "fga_e_pace",
  "fga_rs_on_off_pie", "fga_rs_on_on_ast_pct", "fga_rs_on_off_ast_pct", "fga_opp_pos_on_off_pie",
  "fga_team_pie", "fga_rs_on_off_ast_ratio", "fga_opp_rs_3p_freq", "fga_opp_pos_on_on_pie",
  "fga_rs_on_off_tm_tov_pct", "fga_team_def_rating", "fga_opponent_off_rating", "fga_opponent_dreb_pct",
  "fga_opponent_ts_pct", "fga_rs_on_on_tm_tov_pct", "fga_poss", "fga_passes_per_min",
  "fga_rs_drive_fg_pct", "fga_rs_on_on_ast_to", "fga_rs_on_off_ast_to", "fga_def_rating",
  "fga_e_def_rating", "fga_speed_x_min", "fga_dist", "fga_rs_on_on_pts",
  "fga_rs_on_on_fga", "fga_rs_on_on_reb", "fga_rs_on_on_dreb", "fga_rs_on_on_fgm",
  "fga_rs_on_on_pfd", "fga_rs_paint_touch_fg_pct", "fga_team_ast", "fga_rs_on_on_fta",
  "fga_rs_on_on_ftm", "fga_rs_on_on_fg3a", "fga_rs_on_on_fg3m", "fga_rs_on_on_oreb",
  "fga_opp_pos_on_off_pf", "fga_rs_cs_fg3_pct", "poss_pie", "fgm_opp_rs_lt10f_freq",
  "poss_rs_on_on_fgm", "poss_rs_on_on_fta", "nba_fantasy_pts_pace_per40", "poss_rs_paint_fga",
  "ast_pct_ast", "ast_pct_defensive_activity", "composite_hv_touch_pct", "composite_o_ast_conversion_pct",
  "composite_o_contest_share", "composite_o_oreb_c", "composite_o_uncontest_share", "composite_speed_x_min",
  "composite_weighted_fg_pct", "dist_pct_pts_3pt", "efg_pct_player_touches", "fg3m_pct_fga_2pt",
  "fga_player_game_bench_min", "fga_rs_paint_fgm", "fgm_min_numeric", "fgm_opp_pos_on_off_def_rating",
  "fgm_passes_per_touch", "fgm_player_game_bench_min", "fgm_player_game_contest_share", "fgm_player_game_dist_minus_expected",
  "fgm_player_game_dreb_c_ratio", "fgm_player_game_reb_c_per_min", "fgm_player_game_speed_per_poss", "fgm_player_game_starter_min",
  "fgm_player_game_touches_per_poss", "fgm_player_game_u_fg_pct", "fgm_player_game_uncontest_share", "fgm_player_game_weighted_fg_pct",
  "fgm_pt_cut_poss_weighted_ppp", "fgm_pt_handler_poss_weighted_ppp", "fgm_pt_handoff_poss_weighted_ppp", "fgm_pt_iso_poss_weighted_ppp",
  "fgm_pt_mis_poss_weighted_ppp", "fgm_pt_offscreen_poss_weighted_ppp", "fgm_pt_postup_poss_weighted_ppp", "fgm_pt_putback_poss_weighted_ppp",
  "fgm_pt_rollman_poss_weighted_ppp", "fgm_pt_spotup_poss_weighted_ppp", "fgm_pt_transition_poss_weighted_ppp", "fgm_rs_cs_efg_pct",
  "fgm_series_number", "fgm_team_pie", "fgm_total_line", "ftm_speed_x_min",
  "ftm_u_fg_pct", "ftm_uncontest_share", "min_share_of_game_pt_handler_adj_ppp", "min_uncontest_share",
  "nba_fantasy_pts_uncontest_share", "off_rating_touches", "opponent_vs_player_pts_allowed_c_fg_pct", "opponent_vs_player_pts_allowed_passes_x_contest_share",
  "opponent_vs_player_pts_allowed_touches", "opponent_vs_player_pts_allowed_u_fg_pct", "opponent_vs_player_pts_allowed_weighted_fg_pct", "passes_touch_x_ast_conv",
  "pct_pts_3pt_ast", "pct_pts_3pt_c_fg_pct", "pct_pts_3pt_passes", "pct_pts_3pt_passes_x_contest_share",
  "pfd_total_line", "player_game_pts_per75_rs_on_on_pts", "poss_player_game_bench_min", "poss_player_game_dist",
  "poss_player_game_pts_per75", "poss_pt_cut_adj_ppp", "poss_pt_handoff_adj_ppp", "poss_pt_iso_poss_weighted_ppp",
  "poss_pt_mis_adj_ppp", "poss_pt_offscreen_poss_weighted_ppp", "poss_pt_postup_adj_ppp", "poss_pt_putback_adj_ppp",
  "poss_pt_spotup_adj_ppp", "poss_rs_drive_pts_pct", "poss_u_fg_pct", "pt_cut_poss_per_g_opponent_dreb_pct",
  "pt_cut_poss_per_g_pt_rollman_poss_per_g", "pt_cut_poss_per_g_rs_onoff_pace_diff", "pt_handler_poss_per_g_min_share_of_game", "pt_handler_poss_per_g_total_line",
  "pt_handoff_poss_per_g_team_pace", "pt_iso_poss_per_g_min_share_of_game", "pt_iso_poss_per_g_pt_handler_poss_per_g", "pt_iso_poss_per_g_pt_spotup_poss_per_g",
  "pt_iso_poss_per_g_rs_onoff_net_rating_diff", "pt_iso_poss_per_g_total_line", "pt_iso_ppp_player_game_opponent_vs_player_fgm_allowed_per75", "pt_iso_ppp_rs_on_on_ts_pct",
  "pt_iso_ppp_rs_onoff_net_rating_diff", "pt_iso_ppp_team_net_rating", "pt_iso_ppp_total_line", "pt_mis_poss_per_g_team_pace",
  "pt_offscreen_poss_per_g_team_pace", "pt_postup_poss_per_g_team_pace", "pt_postup_ppp_opp_rs_2p_freq", "pt_postup_ppp_pt_iso_ppp",
  "pt_putback_poss_per_g_team_pace", "pt_rollman_poss_per_g_team_pace", "pt_rollman_ppp_opp_rs_lt6f_freq", "pt_spotup_poss_per_g_opp_rs_3p_freq",
  "pt_spotup_poss_per_g_player_game_fg3a_per_poss", "pt_spotup_ppp_opp_rs_3p_freq", "pt_spotup_ppp_player_game_is_bench", "pt_spotup_ppp_player_game_opponent_vs_player_pts_allowed_per75",
  "pt_transition_poss_per_g_min_share_of_game", "pt_transition_poss_per_g_player_game_passes_per_poss", "pt_transition_poss_per_g_spread_line", "pt_transition_poss_per_g_team_pace",
  "pt_transition_poss_per_g_total_line", "pt_transition_ppp_opponent_tm_tov_pct", "pt_transition_ppp_player_game_speed", "pt_transition_ppp_pt_spotup_ppp",
  "rs_cs_fg3a_touches", "rs_on_on_fgm_usage_rate", "rs_on_on_pfd_ts_pct", "touches_total_line",
  "touches_u_fg_pct", "touches_weighted_fg_pct",
]


EXTRA_FEATURES: List[str] = [
    "team_win_streak", "team_losing_streak", "team_road_trip_length", "team_is_back_to_back",
    "team_is_home", "team_is_three_in_four", "team_is_five_in_seven", "opponent_win_streak",
    "opponent_losing_streak", "opponent_is_back_to_back", "opponent_is_three_in_four", "min5_travel_distance",
    "usage5_b2b", "rolling_minutes_std", "rolling_minutes_std_sq", "player_rest_days",
    "team_rest_days", "opponent_team_rest_days", "rest_days_diff", "pace_gap",
    "fgm_trend_pace_gap", "pts5_per_opp_def_rating", "fgm_fg3m_trend_adj_opp_pts_allowed", "is_hot_streak",
    "is_cold_streak", "is_playoffs", "playoff_round", 
    "series_record", "is_elimination_game", "has_home_court", "can_win_series",
    "is_game_6", "is_game_7", "series_score_diff", "series_prev_game_margin",
    "player_position_number", "composite", "composite_o", "composite_d",
    "composite_rank", "composite_o_rank", "composite_d_rank",
    "rs_cs_fg3a", "rs_cs_fg3_pct", "rs_cs_efg_pct", "rs_pu_fga",
    "rs_pu_efg_pct", "rs_drives", "rs_drive_pts_pct", "rs_drive_fg_pct",
    "rs_drive_ast_pct", "rs_drive_fga", "rs_paint_touches", "rs_paint_touch_fg_pct",
    "rs_paint_touch_pts_pct", "rs_paint_touch_passes_pct", "rs_post_touches", "rs_post_touch_fg_pct",
    "rs_post_touch_pts_pct", "rs_post_touch_ast_pct", "rs_ab_fg_pct", "rs_ab_fga",
    "rs_ab_fgm", "rs_bc_fg_pct", "rs_bc_fga", "rs_bc_fgm",
    "rs_c3_fg_pct", "rs_c3_fga", "rs_c3_fgm", "rs_paint_fg_pct",
    "rs_paint_fga", "rs_paint_fgm", "rs_lc3_fg_pct", "rs_lc3_fga",
    "rs_lc3_fgm", "rs_mr_fg_pct", "rs_mr_fga", "rs_mr_fgm",
    "rs_ra_fg_pct", "rs_ra_fga", "rs_ra_fgm", "rs_rc3_fg_pct",
    "rs_rc3_fga", "rs_rc3_fgm", "opp_rs_d_fg_pct", "opp_rs_d_fga",
    "opp_rs_d_fgm", "opp_rs_ov_pct_plusminus", "opp_rs_2p_freq", "opp_rs_2p_plusminus",
    "opp_rs_3p_freq", "opp_rs_3p_plusminus", "opp_rs_lt6f_freq", "opp_rs_lt6f_plusminus",
    "opp_rs_lt10f_freq", "opp_rs_lt10f_plusminus", "opp_rs_gt15f_freq", "opp_rs_gt15f_plusminus",
    "opp_rs_lt_06_pct", "opp_rs_lt_10_pct", "opp_rs_gt_15_pct", "opp_rs_fg2_pct",
    "opp_rs_fg3_pct","rs_on_on_pace", "rs_on_on_poss", "rs_on_on_net_rating", "rs_on_on_off_rating",
    "rs_on_on_def_rating", "rs_on_on_ts_pct", "rs_on_on_efg_pct", "rs_on_on_pie",
    "rs_on_on_tm_tov_pct", "rs_on_on_pts", "rs_on_on_ast_pct", "rs_on_on_fga",
    "rs_on_on_fg3a", "rs_on_on_fta", "rs_on_on_fgm", "rs_on_on_fg3m",
    "rs_on_on_ftm", "rs_on_on_plus_minus", "rs_on_on_ast_ratio", "rs_on_on_ast_to",
    "rs_on_on_pf", "rs_on_on_pfd", "rs_on_on_oreb", "rs_on_on_dreb", "rs_on_on_reb",
    "rs_on_off_pace", "rs_on_off_poss", "rs_on_off_net_rating", "rs_on_off_off_rating",
    "rs_on_off_def_rating", "rs_on_off_ts_pct", "rs_on_off_efg_pct", "rs_on_off_pie",
    "rs_on_off_tm_tov_pct", "rs_on_off_pts", "rs_on_off_ast_pct", "rs_on_off_fga",
    "rs_on_off_fg3a", "rs_on_off_fta", "rs_on_off_fgm", "rs_on_off_fg3m",
    "rs_on_off_ftm", "rs_on_off_plus_minus", "rs_on_off_ast_ratio", "rs_on_off_ast_to",
    "rs_on_off_pf", "rs_on_off_pfd", "rs_on_off_oreb", "rs_on_off_dreb", "rs_on_off_reb",
    "rs_onoff_pace_diff", "rs_onoff_poss_diff", "rs_onoff_net_rating_diff", "rs_onoff_off_rating_diff",
    "rs_onoff_def_rating_diff", "rs_onoff_ts_pct_diff", "rs_onoff_efg_pct_diff", "rs_onoff_pie_diff",
    "rs_onoff_tm_tov_pct_diff", "rs_onoff_pts_diff", "rs_onoff_ast_pct_diff", "rs_onoff_fga_diff",
    "rs_onoff_fg3a_diff", "rs_onoff_fta_diff", "rs_onoff_fgm_diff", "rs_onoff_fg3m_diff",
    "rs_onoff_ftm_diff", "rs_onoff_pm_diff", "rs_onoff_ast_ratio_diff", "rs_onoff_ast_to_diff",
    "rs_onoff_pf_diff", "rs_onoff_pfd_diff", "rs_onoff_oreb_diff", "rs_onoff_dreb_diff", "rs_onoff_reb_diff",
    "opp_pos_on_on_net_rating", "opp_pos_on_on_off_rating", "opp_pos_on_on_def_rating",
    "opp_pos_on_on_pace", "opp_pos_on_on_poss", "opp_pos_on_on_dreb", "opp_pos_on_on_pie", "opp_pos_on_on_pf",
    "player_game_is_starter", "player_game_is_injury", "player_age", "player_height", "player_weight", "player_greatest_75",
    "player_is_star", "p_ml", "abs_spread", "teim", "opim", "over_odds", "under_odds",
    "moneyline_odds", "spread_line", "total_line", "over_odds", "under_odds", "player_draft_round", "player_draft_number",
    "player_game_is_bench",  "player_game_is_available", "star2_out_flag", "star1_out_flag",
    "pt_handler_adj_percentile", "pt_handler_adj_poss", "pt_handler_adj_ppp", "pt_handler_adj_pts", "pt_handler_efg_pct",
    "pt_handler_fga", "pt_handler_fga_per_g", "pt_handler_fga_percentile", "pt_handler_fgm", "pt_handler_fgm_x",
    "pt_handler_fg_pct", "pt_handler_ft_poss_pct", "pt_handler_gp", "pt_handler_percentile", "pt_handler_plusone_poss_pct",
    "pt_handler_poe", "pt_handler_poe_per_g", "pt_handler_poe_rank", "pt_handler_poss", "pt_handler_poss_per_g",
    "pt_handler_poss_percentile", "pt_handler_poss_weighted_ppp", "pt_handler_ppp", "pt_handler_pts", "pt_handler_score_poss_pct",
    "pt_handler_sf_poss_pct", "pt_handler_tov_poss_pct", "pt_handler_rppp", "pt_iso_adj_percentile", "pt_iso_adj_poss",
    "pt_iso_adj_ppp", "pt_iso_adj_pts", "pt_iso_efg_pct", "pt_iso_fga", "pt_iso_fga_per_g",
    "pt_iso_fga_percentile", "pt_iso_fgm", "pt_iso_fgm_x", "pt_iso_fg_pct", "pt_iso_ft_poss_pct",
    "pt_iso_gp", "pt_iso_percentile", "pt_iso_plusone_poss_pct", "pt_iso_poe", "pt_iso_poe_per_g",
    "pt_iso_poe_rank", "pt_iso_poss", "pt_iso_poss_per_g", "pt_iso_poss_percentile", "pt_iso_poss_weighted_ppp",
    "pt_iso_ppp", "pt_iso_pts", "pt_iso_score_poss_pct", "pt_iso_sf_poss_pct", "pt_iso_tov_poss_pct",
    "pt_iso_rppp", "pt_transition_adj_percentile", "pt_transition_adj_poss", "pt_transition_adj_ppp", "pt_transition_adj_pts",
    "pt_transition_efg_pct", "pt_transition_fga", "pt_transition_fga_per_g", "pt_transition_fga_percentile", "pt_transition_fgm",
    "pt_transition_fgm_x", "pt_transition_fg_pct", "pt_transition_ft_poss_pct", "pt_transition_gp", "pt_transition_percentile",
    "pt_transition_plusone_poss_pct", "pt_transition_poe", "pt_transition_poe_per_g", "pt_transition_poe_rank", "pt_transition_poss",
    "pt_transition_poss_per_g", "pt_transition_poss_percentile", "pt_transition_poss_weighted_ppp", "pt_transition_ppp", "pt_transition_pts",
    "pt_transition_score_poss_pct", "pt_transition_sf_poss_pct", "pt_transition_tov_poss_pct", "pt_transition_rppp",
    "pt_mis_adj_percentile", "pt_mis_adj_poss", "pt_mis_adj_ppp", "pt_mis_adj_pts", "pt_mis_efg_pct",
    "pt_mis_fga", "pt_mis_fga_per_g", "pt_mis_fga_percentile", "pt_mis_fgm", "pt_mis_fgm_x",
    "pt_mis_fg_pct", "pt_mis_ft_poss_pct", "pt_mis_gp", "pt_mis_percentile", "pt_mis_plusone_poss_pct",
    "pt_mis_poe", "pt_mis_poe_per_g", "pt_mis_poe_rank", "pt_mis_poss", "pt_mis_poss_per_g",
    "pt_mis_poss_percentile", "pt_mis_poss_weighted_ppp", "pt_mis_ppp", "pt_mis_pts", "pt_mis_score_poss_pct",
    "pt_mis_sf_poss_pct", "pt_mis_tov_poss_pct", "pt_mis_rppp", "pt_postup_adj_percentile", "pt_postup_adj_poss",
    "pt_postup_adj_ppp", "pt_postup_adj_pts", "pt_postup_efg_pct", "pt_postup_fga", "pt_postup_fga_per_g",
    "pt_postup_fga_percentile", "pt_postup_fgm", "pt_postup_fgm_x", "pt_postup_fg_pct", "pt_postup_ft_poss_pct",
    "pt_postup_gp", "pt_postup_percentile", "pt_postup_plusone_poss_pct", "pt_postup_poe", "pt_postup_poe_per_g",
    "pt_postup_poe_rank", "pt_postup_poss", "pt_postup_poss_per_g", "pt_postup_poss_percentile", "pt_postup_poss_weighted_ppp",
    "pt_postup_ppp", "pt_postup_pts", "pt_postup_score_poss_pct", "pt_postup_sf_poss_pct", "pt_postup_tov_poss_pct",
    "pt_postup_rppp", "pt_spotup_adj_percentile", "pt_spotup_adj_poss", "pt_spotup_adj_ppp", "pt_spotup_adj_pts",
    "pt_spotup_efg_pct", "pt_spotup_fga", "pt_spotup_fga_per_g", "pt_spotup_fga_percentile", "pt_spotup_fgm",
    "pt_spotup_fgm_x", "pt_spotup_fg_pct", "pt_spotup_ft_poss_pct", "pt_spotup_gp", "pt_spotup_percentile",
    "pt_spotup_plusone_poss_pct", "pt_spotup_poe", "pt_spotup_poe_per_g", "pt_spotup_poe_rank", "pt_spotup_poss",
    "pt_spotup_poss_per_g", "pt_spotup_poss_percentile", "pt_spotup_poss_weighted_ppp", "pt_spotup_ppp", "pt_spotup_pts",
    "pt_spotup_score_poss_pct", "pt_spotup_sf_poss_pct", "pt_spotup_tov_poss_pct", "pt_spotup_rppp", "pt_handoff_adj_percentile",
    "pt_handoff_adj_poss", "pt_handoff_adj_ppp", "pt_handoff_adj_pts", "pt_handoff_efg_pct", "pt_handoff_fga",
    "pt_handoff_fga_per_g", "pt_handoff_fga_percentile", "pt_handoff_fgm", "pt_handoff_fgm_x", "pt_handoff_fg_pct",
    "pt_handoff_ft_poss_pct", "pt_handoff_gp", "pt_handoff_percentile", "pt_handoff_plusone_poss_pct", "pt_handoff_poe",
    "pt_handoff_poe_per_g", "pt_handoff_poe_rank", "pt_handoff_poss", "pt_handoff_poss_per_g", "pt_handoff_poss_percentile",
    "pt_handoff_poss_weighted_ppp", "pt_handoff_ppp", "pt_handoff_pts", "pt_handoff_score_poss_pct", "pt_handoff_sf_poss_pct",
    "pt_handoff_tov_poss_pct", "pt_handoff_rppp",
    "pt_offscreen_adj_percentile", "pt_offscreen_adj_poss", "pt_offscreen_adj_ppp", "pt_offscreen_adj_pts", "pt_offscreen_efg_pct",
    "pt_offscreen_fga", "pt_offscreen_fga_per_g", "pt_offscreen_fga_percentile", "pt_offscreen_fgm", "pt_offscreen_fgm_x",
    "pt_offscreen_fg_pct", "pt_offscreen_ft_poss_pct", "pt_offscreen_gp", "pt_offscreen_percentile", "pt_offscreen_plusone_poss_pct",
    "pt_offscreen_poe", "pt_offscreen_poe_per_g", "pt_offscreen_poe_rank", "pt_offscreen_poss", "pt_offscreen_poss_per_g",
    "pt_offscreen_poss_percentile", "pt_offscreen_poss_weighted_ppp", "pt_offscreen_ppp", "pt_offscreen_pts", "pt_offscreen_score_poss_pct",
    "pt_offscreen_sf_poss_pct", "pt_offscreen_tov_poss_pct", "pt_offscreen_rppp", "pt_cut_adj_percentile", "pt_cut_adj_poss",
    "pt_cut_adj_ppp", "pt_cut_adj_pts", "pt_cut_efg_pct", "pt_cut_fga", "pt_cut_fga_per_g",
    "pt_cut_fga_percentile", "pt_cut_fgm", "pt_cut_fgm_x", "pt_cut_fg_pct", "pt_cut_ft_poss_pct",
    "pt_cut_gp", "pt_cut_percentile", "pt_cut_plusone_poss_pct", "pt_cut_poe", "pt_cut_poe_per_g",
    "pt_cut_poe_rank", "pt_cut_poss", "pt_cut_poss_per_g", "pt_cut_poss_percentile", "pt_cut_poss_weighted_ppp",
    "pt_cut_ppp", "pt_cut_pts", "pt_cut_score_poss_pct", "pt_cut_sf_poss_pct", "pt_cut_tov_poss_pct",
    "pt_cut_rppp", "pt_putback_adj_percentile", "pt_putback_adj_poss", "pt_putback_adj_ppp", "pt_putback_adj_pts",
    "pt_putback_efg_pct", "pt_putback_fga", "pt_putback_fga_per_g", "pt_putback_fga_percentile", "pt_putback_fgm",
    "pt_putback_fgm_x", "pt_putback_fg_pct", "pt_putback_ft_poss_pct", "pt_putback_gp", "pt_putback_percentile",
    "pt_putback_plusone_poss_pct", "pt_putback_poe", "pt_putback_poe_per_g", "pt_putback_poe_rank", "pt_putback_poss",
    "pt_putback_poss_per_g", "pt_putback_poss_percentile", "pt_putback_poss_weighted_ppp", "pt_putback_ppp", "pt_putback_pts",
    "pt_putback_score_poss_pct", "pt_putback_sf_poss_pct", "pt_putback_tov_poss_pct", "pt_putback_rppp", "pt_rollman_adj_percentile",
    "pt_rollman_adj_poss", "pt_rollman_adj_ppp", "pt_rollman_adj_pts", "pt_rollman_efg_pct", "pt_rollman_fga",
    "pt_rollman_fga_per_g", "pt_rollman_fga_percentile", "pt_rollman_fgm", "pt_rollman_fgm_x", "pt_rollman_fg_pct",
    "pt_rollman_ft_poss_pct", "pt_rollman_gp", "pt_rollman_percentile", "pt_rollman_plusone_poss_pct", "pt_rollman_poe",
    "pt_rollman_poe_per_g", "pt_rollman_poe_rank", "pt_rollman_poss", "pt_rollman_poss_per_g", "pt_rollman_poss_percentile",
    "pt_rollman_poss_weighted_ppp", "pt_rollman_ppp", "pt_rollman_pts", "pt_rollman_score_poss_pct", "pt_rollman_sf_poss_pct",
    "pt_rollman_tov_poss_pct", "pt_rollman_rppp",
] 

CAT_FLAGS: List[str] = [
    "player_position_number", "season", # Keep season if present
    "team_is_back_to_back", "team_is_home", "team_is_three_in_four",
    "team_is_five_in_seven", "opponent_is_back_to_back", "opponent_is_three_in_four",
    "team_is_high_altitude", "is_hot_streak", "is_cold_streak",
    "is_playoffs", "playoff_round", "series_number", # Raw flags if present
    "series_record", "is_elimination_game", "can_win_series", # Raw flags if present
    "has_home_court", "is_game_6", "is_game_7",
    "series_tied", "player_greatest_75", "fav_flag",
]


PLAYOFF_COLS: List[str] = [
    "is_playoffs", "playoff_round", "series_number",
    "series_record", "is_elimination_game", "can_win_series",
    "has_home_court", "is_game_6", "is_game_7"
]

ODD_COLS_NUMERIC: List[str] = [
    "moneyline_odds", "spread_line", "total_line",
    "over_odds", "under_odds"
]

ODD_COLS: List[str] = [
    "p_ml", "abs_spread", "teim", "opim", "over_odds", "under_odds"
]